// <auto-generated />
using System;
using EduTrack.Data.DBContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EduTrack.Data.Migrations
{
    [DbContext(typeof(EduDbContext))]
    [Migration("20251226125426_InitialCommitWithSeedData")]
    partial class InitialCommitWithSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EduTrack.Domain.Entities.Attendance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("GroupId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPresent")
                        .HasColumnType("bit");

                    b.Property<string>("Remarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.HasIndex("StudentId");

                    b.ToTable("Attendances");
                });

            modelBuilder.Entity("EduTrack.Domain.Entities.Branch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Branches");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Amir Temur St, 123",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Name = "Tashkent Main",
                            PhoneNumber = "+998 71 207-50-50"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Bodomzor St, 45",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Name = "Tashkent East",
                            PhoneNumber = "+998 71 207-60-60"
                        },
                        new
                        {
                            Id = 3,
                            Address = "Registan Sq, 10",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Name = "Samarkand Branch",
                            PhoneNumber = "+998 66 233-00-00"
                        });
                });

            modelBuilder.Entity("EduTrack.Domain.Entities.Group", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BranchId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<decimal>("MonthlyFee")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoomId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TeacherId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BranchId");

                    b.HasIndex("RoomId");

                    b.HasIndex("TeacherId");

                    b.ToTable("Groups");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BranchId = 1,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Beginner level English",
                            EndDate = new DateTime(2025, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            MonthlyFee = 500000m,
                            Name = "English A1 - Morning",
                            RoomId = 1,
                            StartDate = new DateTime(2025, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Subject = "English",
                            TeacherId = 2
                        },
                        new
                        {
                            Id = 2,
                            BranchId = 1,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Elementary level English",
                            EndDate = new DateTime(2025, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            MonthlyFee = 500000m,
                            Name = "English A2 - Evening",
                            RoomId = 2,
                            StartDate = new DateTime(2025, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Subject = "English",
                            TeacherId = 3
                        },
                        new
                        {
                            Id = 3,
                            BranchId = 1,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Intermediate level English",
                            EndDate = new DateTime(2025, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            MonthlyFee = 600000m,
                            Name = "English B1",
                            RoomId = 3,
                            StartDate = new DateTime(2025, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Subject = "English",
                            TeacherId = 4
                        },
                        new
                        {
                            Id = 4,
                            BranchId = 2,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Beginner level English",
                            EndDate = new DateTime(2025, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            MonthlyFee = 500000m,
                            Name = "English A1",
                            RoomId = 4,
                            StartDate = new DateTime(2025, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Subject = "English",
                            TeacherId = 5
                        },
                        new
                        {
                            Id = 5,
                            BranchId = 2,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Intermediate level English",
                            EndDate = new DateTime(2025, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            MonthlyFee = 600000m,
                            Name = "English B1",
                            RoomId = 5,
                            StartDate = new DateTime(2025, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Subject = "English",
                            TeacherId = 6
                        },
                        new
                        {
                            Id = 6,
                            BranchId = 2,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Advanced level English",
                            EndDate = new DateTime(2025, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            MonthlyFee = 700000m,
                            Name = "English C1",
                            RoomId = 6,
                            StartDate = new DateTime(2025, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Subject = "English",
                            TeacherId = 7
                        },
                        new
                        {
                            Id = 7,
                            BranchId = 3,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Beginner level English",
                            EndDate = new DateTime(2025, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            MonthlyFee = 500000m,
                            Name = "English A1",
                            RoomId = 7,
                            StartDate = new DateTime(2025, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Subject = "English",
                            TeacherId = 8
                        },
                        new
                        {
                            Id = 8,
                            BranchId = 3,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Intermediate level English",
                            EndDate = new DateTime(2025, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            MonthlyFee = 600000m,
                            Name = "English B1",
                            RoomId = 8,
                            StartDate = new DateTime(2025, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Subject = "English",
                            TeacherId = 9
                        });
                });

            modelBuilder.Entity("EduTrack.Domain.Entities.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ForMonth")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GroupId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentMethod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.HasIndex("StudentId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("EduTrack.Domain.Entities.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BranchId")
                        .HasColumnType("int");

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BranchId");

                    b.ToTable("Rooms");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BranchId = 1,
                            Capacity = 30,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Main classroom",
                            IsDeleted = false,
                            Name = "Room A1"
                        },
                        new
                        {
                            Id = 2,
                            BranchId = 1,
                            Capacity = 25,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Medium classroom",
                            IsDeleted = false,
                            Name = "Room A2"
                        },
                        new
                        {
                            Id = 3,
                            BranchId = 1,
                            Capacity = 20,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Small classroom",
                            IsDeleted = false,
                            Name = "Room A3"
                        },
                        new
                        {
                            Id = 4,
                            BranchId = 2,
                            Capacity = 30,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Main classroom",
                            IsDeleted = false,
                            Name = "Room B1"
                        },
                        new
                        {
                            Id = 5,
                            BranchId = 2,
                            Capacity = 25,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Medium classroom",
                            IsDeleted = false,
                            Name = "Room B2"
                        },
                        new
                        {
                            Id = 6,
                            BranchId = 2,
                            Capacity = 20,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Small classroom",
                            IsDeleted = false,
                            Name = "Room B3"
                        },
                        new
                        {
                            Id = 7,
                            BranchId = 3,
                            Capacity = 30,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Main classroom",
                            IsDeleted = false,
                            Name = "Room C1"
                        },
                        new
                        {
                            Id = 8,
                            BranchId = 3,
                            Capacity = 25,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Medium classroom",
                            IsDeleted = false,
                            Name = "Room C2"
                        });
                });

            modelBuilder.Entity("EduTrack.Domain.Entities.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ParentPhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Tashkent",
                            BirthDate = new DateTime(2005, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Ali",
                            IsDeleted = false,
                            LastName = "Abdullayev",
                            ParentPhoneNumber = "+998 90 201-11-11",
                            PhoneNumber = "+998 91 101-11-11"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Tashkent",
                            BirthDate = new DateTime(2004, 8, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Zarina",
                            IsDeleted = false,
                            LastName = "Karimova",
                            ParentPhoneNumber = "+998 90 202-11-11",
                            PhoneNumber = "+998 91 102-11-11"
                        },
                        new
                        {
                            Id = 3,
                            Address = "Tashkent",
                            BirthDate = new DateTime(2005, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Jamoliddin",
                            IsDeleted = false,
                            LastName = "Rahimov",
                            ParentPhoneNumber = "+998 90 203-11-11",
                            PhoneNumber = "+998 91 103-11-11"
                        },
                        new
                        {
                            Id = 4,
                            Address = "Tashkent",
                            BirthDate = new DateTime(2003, 12, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Sitora",
                            IsDeleted = false,
                            LastName = "Yusupova",
                            ParentPhoneNumber = "+998 90 204-11-11",
                            PhoneNumber = "+998 91 104-11-11"
                        },
                        new
                        {
                            Id = 5,
                            Address = "Tashkent",
                            BirthDate = new DateTime(2004, 6, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Mirjalol",
                            IsDeleted = false,
                            LastName = "Mirmirov",
                            ParentPhoneNumber = "+998 90 205-11-11",
                            PhoneNumber = "+998 91 105-11-11"
                        },
                        new
                        {
                            Id = 6,
                            Address = "Tashkent",
                            BirthDate = new DateTime(2005, 9, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Dilnoza",
                            IsDeleted = false,
                            LastName = "Sattarova",
                            ParentPhoneNumber = "+998 90 206-11-11",
                            PhoneNumber = "+998 91 106-11-11"
                        },
                        new
                        {
                            Id = 7,
                            Address = "Tashkent",
                            BirthDate = new DateTime(2004, 2, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Navruzbek",
                            IsDeleted = false,
                            LastName = "Kamolov",
                            ParentPhoneNumber = "+998 90 207-11-11",
                            PhoneNumber = "+998 91 107-11-11"
                        },
                        new
                        {
                            Id = 8,
                            Address = "Tashkent",
                            BirthDate = new DateTime(2005, 7, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Gulnara",
                            IsDeleted = false,
                            LastName = "Azimova",
                            ParentPhoneNumber = "+998 90 208-11-11",
                            PhoneNumber = "+998 91 108-11-11"
                        },
                        new
                        {
                            Id = 9,
                            Address = "Tashkent",
                            BirthDate = new DateTime(2003, 11, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Bakhrom",
                            IsDeleted = false,
                            LastName = "Sharipov",
                            ParentPhoneNumber = "+998 90 209-11-11",
                            PhoneNumber = "+998 91 109-11-11"
                        },
                        new
                        {
                            Id = 10,
                            Address = "Tashkent",
                            BirthDate = new DateTime(2004, 4, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Nozim",
                            IsDeleted = false,
                            LastName = "Abdullayev",
                            ParentPhoneNumber = "+998 90 210-11-11",
                            PhoneNumber = "+998 91 110-11-11"
                        },
                        new
                        {
                            Id = 11,
                            Address = "Tashkent",
                            BirthDate = new DateTime(2005, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Marya",
                            IsDeleted = false,
                            LastName = "Rustamova",
                            ParentPhoneNumber = "+998 90 211-11-11",
                            PhoneNumber = "+998 91 111-11-11"
                        },
                        new
                        {
                            Id = 12,
                            Address = "Tashkent",
                            BirthDate = new DateTime(2004, 10, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Timur",
                            IsDeleted = false,
                            LastName = "Nasimov",
                            ParentPhoneNumber = "+998 90 212-11-11",
                            PhoneNumber = "+998 91 112-11-11"
                        },
                        new
                        {
                            Id = 13,
                            Address = "Tashkent",
                            BirthDate = new DateTime(2005, 2, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Yasmin",
                            IsDeleted = false,
                            LastName = "Ergasheva",
                            ParentPhoneNumber = "+998 90 213-11-11",
                            PhoneNumber = "+998 91 113-11-11"
                        },
                        new
                        {
                            Id = 14,
                            Address = "Tashkent",
                            BirthDate = new DateTime(2003, 9, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Fazliddin",
                            IsDeleted = false,
                            LastName = "Qurbonov",
                            ParentPhoneNumber = "+998 90 214-11-11",
                            PhoneNumber = "+998 91 114-11-11"
                        },
                        new
                        {
                            Id = 15,
                            Address = "Tashkent",
                            BirthDate = new DateTime(2004, 12, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Umida",
                            IsDeleted = false,
                            LastName = "Sultonova",
                            ParentPhoneNumber = "+998 90 215-11-11",
                            PhoneNumber = "+998 91 115-11-11"
                        },
                        new
                        {
                            Id = 16,
                            Address = "Tashkent",
                            BirthDate = new DateTime(2005, 4, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Maxim",
                            IsDeleted = false,
                            LastName = "Petrov",
                            ParentPhoneNumber = "+998 90 216-11-11",
                            PhoneNumber = "+998 91 116-11-11"
                        },
                        new
                        {
                            Id = 17,
                            Address = "Tashkent",
                            BirthDate = new DateTime(2004, 7, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Irina",
                            IsDeleted = false,
                            LastName = "Volkova",
                            ParentPhoneNumber = "+998 90 217-11-11",
                            PhoneNumber = "+998 91 117-11-11"
                        },
                        new
                        {
                            Id = 18,
                            Address = "Tashkent",
                            BirthDate = new DateTime(2005, 8, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Dmitri",
                            IsDeleted = false,
                            LastName = "Sokolov",
                            ParentPhoneNumber = "+998 90 218-11-11",
                            PhoneNumber = "+998 91 118-11-11"
                        },
                        new
                        {
                            Id = 19,
                            Address = "Tashkent",
                            BirthDate = new DateTime(2004, 9, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Ekaterina",
                            IsDeleted = false,
                            LastName = "Kuznetsova",
                            ParentPhoneNumber = "+998 90 219-11-11",
                            PhoneNumber = "+998 91 119-11-11"
                        },
                        new
                        {
                            Id = 20,
                            Address = "Tashkent",
                            BirthDate = new DateTime(2005, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Vladimir",
                            IsDeleted = false,
                            LastName = "Smirnov",
                            ParentPhoneNumber = "+998 90 220-11-11",
                            PhoneNumber = "+998 91 120-11-11"
                        },
                        new
                        {
                            Id = 21,
                            Address = "Tashkent",
                            BirthDate = new DateTime(2004, 11, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Olga",
                            IsDeleted = false,
                            LastName = "Ivanova",
                            ParentPhoneNumber = "+998 90 221-11-11",
                            PhoneNumber = "+998 91 121-11-11"
                        },
                        new
                        {
                            Id = 22,
                            Address = "Samarkand",
                            BirthDate = new DateTime(2005, 6, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Sergei",
                            IsDeleted = false,
                            LastName = "Lebedev",
                            ParentPhoneNumber = "+998 90 222-11-11",
                            PhoneNumber = "+998 91 122-11-11"
                        },
                        new
                        {
                            Id = 23,
                            Address = "Samarkand",
                            BirthDate = new DateTime(2004, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Natalia",
                            IsDeleted = false,
                            LastName = "Morozova",
                            ParentPhoneNumber = "+998 90 223-11-11",
                            PhoneNumber = "+998 91 123-11-11"
                        },
                        new
                        {
                            Id = 24,
                            Address = "Samarkand",
                            BirthDate = new DateTime(2005, 3, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Andrey",
                            IsDeleted = false,
                            LastName = "Orlov",
                            ParentPhoneNumber = "+998 90 224-11-11",
                            PhoneNumber = "+998 91 124-11-11"
                        },
                        new
                        {
                            Id = 25,
                            Address = "Samarkand",
                            BirthDate = new DateTime(2004, 5, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Valentina",
                            IsDeleted = false,
                            LastName = "Popova",
                            ParentPhoneNumber = "+998 90 225-11-11",
                            PhoneNumber = "+998 91 125-11-11"
                        },
                        new
                        {
                            Id = 26,
                            Address = "Samarkand",
                            BirthDate = new DateTime(2005, 11, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Mahmud",
                            IsDeleted = false,
                            LastName = "Hakimov",
                            ParentPhoneNumber = "+998 90 226-11-11",
                            PhoneNumber = "+998 91 126-11-11"
                        },
                        new
                        {
                            Id = 27,
                            Address = "Samarkand",
                            BirthDate = new DateTime(2004, 3, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Svetlana",
                            IsDeleted = false,
                            LastName = "Sorokin",
                            ParentPhoneNumber = "+998 90 227-11-11",
                            PhoneNumber = "+998 91 127-11-11"
                        },
                        new
                        {
                            Id = 28,
                            Address = "Samarkand",
                            BirthDate = new DateTime(2005, 12, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Kamol",
                            IsDeleted = false,
                            LastName = "Fayziev",
                            ParentPhoneNumber = "+998 90 228-11-11",
                            PhoneNumber = "+998 91 128-11-11"
                        });
                });

            modelBuilder.Entity("EduTrack.Domain.Entities.StudentGroup", b =>
                {
                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<int>("GroupId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("StudentId", "GroupId");

                    b.HasIndex("GroupId");

                    b.ToTable("StudentGroups");

                    b.HasData(
                        new
                        {
                            StudentId = 1,
                            GroupId = 1,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Id = 0,
                            IsDeleted = false
                        },
                        new
                        {
                            StudentId = 2,
                            GroupId = 1,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Id = 0,
                            IsDeleted = false
                        },
                        new
                        {
                            StudentId = 3,
                            GroupId = 1,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Id = 0,
                            IsDeleted = false
                        },
                        new
                        {
                            StudentId = 4,
                            GroupId = 1,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Id = 0,
                            IsDeleted = false
                        });
                });

            modelBuilder.Entity("EduTrack.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "john@edutrack.uz",
                            FirstName = "John",
                            IsDeleted = false,
                            LastName = "Smith",
                            PasswordHash = "$2a$11$abcdefghijklmnopqrstuvwxyz1234567890abcdefghijklmnopqrst",
                            PhoneNumber = "+998 90 100-00-00",
                            Role = 0
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "fatima@edutrack.uz",
                            FirstName = "Fatima",
                            IsDeleted = false,
                            LastName = "Karimova",
                            PasswordHash = "$2a$11$abcdefghijklmnopqrstuvwxyz1234567890abcdefghijklmnopqrst",
                            PhoneNumber = "+998 90 111-11-11",
                            Role = 1
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "alisher@edutrack.uz",
                            FirstName = "Alisher",
                            IsDeleted = false,
                            LastName = "Juraev",
                            PasswordHash = "$2a$11$abcdefghijklmnopqrstuvwxyz1234567890abcdefghijklmnopqrst",
                            PhoneNumber = "+998 90 222-22-22",
                            Role = 1
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "sardor@edutrack.uz",
                            FirstName = "Sardor",
                            IsDeleted = false,
                            LastName = "Rashidov",
                            PasswordHash = "$2a$11$abcdefghijklmnopqrstuvwxyz1234567890abcdefghijklmnopqrst",
                            PhoneNumber = "+998 90 333-33-33",
                            Role = 1
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "nafisa@edutrack.uz",
                            FirstName = "Nafisa",
                            IsDeleted = false,
                            LastName = "Abdullayeva",
                            PasswordHash = "$2a$11$abcdefghijklmnopqrstuvwxyz1234567890abcdefghijklmnopqrst",
                            PhoneNumber = "+998 90 444-44-44",
                            Role = 1
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "oleg@edutrack.uz",
                            FirstName = "Oleg",
                            IsDeleted = false,
                            LastName = "Petrov",
                            PasswordHash = "$2a$11$abcdefghijklmnopqrstuvwxyz1234567890abcdefghijklmnopqrst",
                            PhoneNumber = "+998 90 555-55-55",
                            Role = 1
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "nozima@edutrack.uz",
                            FirstName = "Nozima",
                            IsDeleted = false,
                            LastName = "Iskandarova",
                            PasswordHash = "$2a$11$abcdefghijklmnopqrstuvwxyz1234567890abcdefghijklmnopqrst",
                            PhoneNumber = "+998 90 666-66-66",
                            Role = 1
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "rustam@edutrack.uz",
                            FirstName = "Rustam",
                            IsDeleted = false,
                            LastName = "Nosirov",
                            PasswordHash = "$2a$11$abcdefghijklmnopqrstuvwxyz1234567890abcdefghijklmnopqrst",
                            PhoneNumber = "+998 90 777-77-77",
                            Role = 1
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "yulduz@edutrack.uz",
                            FirstName = "Yulduz",
                            IsDeleted = false,
                            LastName = "Karimova",
                            PasswordHash = "$2a$11$abcdefghijklmnopqrstuvwxyz1234567890abcdefghijklmnopqrst",
                            PhoneNumber = "+998 90 888-88-88",
                            Role = 1
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "dilshod@edutrack.uz",
                            FirstName = "Dilshod",
                            IsDeleted = false,
                            LastName = "Akramov",
                            PasswordHash = "$2a$11$abcdefghijklmnopqrstuvwxyz1234567890abcdefghijklmnopqrst",
                            PhoneNumber = "+998 90 999-99-99",
                            Role = 1
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "elena@edutrack.uz",
                            FirstName = "Elena",
                            IsDeleted = false,
                            LastName = "Volkova",
                            PasswordHash = "$2a$11$abcdefghijklmnopqrstuvwxyz1234567890abcdefghijklmnopqrst",
                            PhoneNumber = "+998 90 101-01-01",
                            Role = 1
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "gulnoza@edutrack.uz",
                            FirstName = "Gulnoza",
                            IsDeleted = false,
                            LastName = "Abdullayeva",
                            PasswordHash = "Manager@123",
                            PhoneNumber = "+998 91 100-00-00",
                            Role = 2
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "aziz@edutrack.uz",
                            FirstName = "Aziz",
                            IsDeleted = false,
                            LastName = "Khusnutdinov",
                            PasswordHash = "Manager@123",
                            PhoneNumber = "+998 91 200-00-00",
                            Role = 2
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "lola@edutrack.uz",
                            FirstName = "Lola",
                            IsDeleted = false,
                            LastName = "Mirjalieva",
                            PasswordHash = "Manager@123",
                            PhoneNumber = "+998 91 300-00-00",
                            Role = 2
                        });
                });

            modelBuilder.Entity("EduTrack.Domain.Entities.Attendance", b =>
                {
                    b.HasOne("EduTrack.Domain.Entities.Group", "Group")
                        .WithMany("Attendances")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("EduTrack.Domain.Entities.Student", "Student")
                        .WithMany("Attendances")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("EduTrack.Domain.Entities.Group", b =>
                {
                    b.HasOne("EduTrack.Domain.Entities.Branch", "Branch")
                        .WithMany("Groups")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("EduTrack.Domain.Entities.Room", "Room")
                        .WithMany("Groups")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("EduTrack.Domain.Entities.User", "Teacher")
                        .WithMany("Groups")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Branch");

                    b.Navigation("Room");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("EduTrack.Domain.Entities.Payment", b =>
                {
                    b.HasOne("EduTrack.Domain.Entities.Group", "Group")
                        .WithMany("Payments")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("EduTrack.Domain.Entities.Student", "Student")
                        .WithMany("Payments")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("EduTrack.Domain.Entities.Room", b =>
                {
                    b.HasOne("EduTrack.Domain.Entities.Branch", "Branch")
                        .WithMany("Rooms")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Branch");
                });

            modelBuilder.Entity("EduTrack.Domain.Entities.StudentGroup", b =>
                {
                    b.HasOne("EduTrack.Domain.Entities.Group", "Group")
                        .WithMany("StudentGroups")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EduTrack.Domain.Entities.Student", "Student")
                        .WithMany("StudentGroups")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("EduTrack.Domain.Entities.Branch", b =>
                {
                    b.Navigation("Groups");

                    b.Navigation("Rooms");
                });

            modelBuilder.Entity("EduTrack.Domain.Entities.Group", b =>
                {
                    b.Navigation("Attendances");

                    b.Navigation("Payments");

                    b.Navigation("StudentGroups");
                });

            modelBuilder.Entity("EduTrack.Domain.Entities.Room", b =>
                {
                    b.Navigation("Groups");
                });

            modelBuilder.Entity("EduTrack.Domain.Entities.Student", b =>
                {
                    b.Navigation("Attendances");

                    b.Navigation("Payments");

                    b.Navigation("StudentGroups");
                });

            modelBuilder.Entity("EduTrack.Domain.Entities.User", b =>
                {
                    b.Navigation("Groups");
                });
#pragma warning restore 612, 618
        }
    }
}
